# Generated by Django 4.2.1 on 2023-06-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
